various changes (WORK IN PROGRESS)
10XGenomics/enclone pull request #217
Opened 2021-03-10 13:28 UTC by DavidBJaffe

- find some files in modified aggr pipeline

2021-03-15 22:38 UTC, wyattmcdonnell requested changes
Things to look at before merge:

* Crate duplication: `amino` `0.1.5`,`0.1`; `ansi_escape` `0.1` `0.1.1`; `fs_extra` `1.1` `1.2.0`
* Remove lines 117-120 in `enclone/src/UNDOC_OPTIONS`
* Remove line 179 in `enclone/src/UNDOC_OPTIONS`
* Edit lines 361-366 in `enclone_help/src/help5.rs`
* Recommend `/bin/sh` or `/usr/bin/env bash` for `speed` shebang
* Edit line 762 in `enclone_main/tests/enclone_test2.rs`
* Edit line 706 in `enclone_main/tests/enclone_test2.rs`

2021-03-15 22:38 UTC, wyattmcdonnell commented on enclone_main/tests/enclone_test_peak_mem.rs
> +// Test peak memory.  This is designed for one server, bespin1.
```suggestion
// This is designed for one internal development server.
```

2021-03-15 22:38 UTC, wyattmcdonnell commented on enclone_main/tests/enclone_test_peak_mem.rs
> +            3. Repeat the test, but this is very unlikely to succeed.\n",
🚩

2021-03-15 22:38 UTC, wyattmcdonnell commented on testx
> +# ./testx is a version of ./test that should run anywere
```suggestion
# ./testx is a version of ./test that should run anywhere
```

2021-03-15 22:38 UTC, wyattmcdonnell commented on testx
> +#!/bin/csh
Recommend one of the following:
```suggestion
#!/bin/sh
```
```suggestion
#/usr/bin/env bash
```

2021-03-15 22:38 UTC, wyattmcdonnell commented on pages/dev.html.src
> +<p>#enclone is written in rust.</p>
```suggestion
<p>#enclone is written in Rust.</p>
```

2021-03-15 22:38 UTC, wyattmcdonnell commented on pages/dev.html.src
> +<p>Technical details.  The repo is itself a rust workspace, with a half dozen or so
```suggestion
<p>We used Rust because the language makes it extremely easy to use Rust code written by
other people, because Rust has its own build system, and because it is fast and safe.</p>
 
<p>Technical details.  The repo is itself a Rust workspace, with a half dozen or so
```

2021-03-15 22:38 UTC, wyattmcdonnell commented on pages/dev.html.src
> +<code>cargo install cargo-license</code>, assuming that you have already installed rust.</li>
```suggestion
<code>cargo install cargo-license</code>, assuming that you have already installed Rust.</li>
```

2021-03-16 02:51 UTC, DavidBJaffe commented
Directly checking `Cargo.lock` suggests e.g. that the crate `amino` is not duplicated.  Where do you see the duplication?  And `./test` actually tests for duplication!

2021-03-16 03:06 UTC, DavidBJaffe commented
OK I think I've made the changes you suggested!

2021-03-16 03:34 UTC, wyattmcdonnell commented on enclone/src/proc_args3.rs
> +                                the slack channel.\nOr retry again.  enclone is \
```suggestion
                                slack channel.\nOr retry again.  enclone is \
```

2021-03-16 03:39 UTC, wyattmcdonnell approved these changes
Excellent, thank you for working through that list!

2021-03-16 13:33 UTC, merged